package com.quizling.shared.dto

/**
 * Dto to start a match
 * @param id the match id, if desired to provide. If not it will be generated by the app
 * @param configuration the match configuration
 */
final case class StartMatchDto(id: Option[String], configuration: MatchConfigurationDto)
